name: Document CI

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'scripts/**'
  pull_request:
    branches: [release]
    paths:
      - 'docs/**'
      - 'scripts/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Validate documents
        run: python scripts/validate_docs.py --repo-root .
